#include <iostream>
using namespace std;

int main(){
	int a, b;
	cin >> a >> b;
	if (a == 1 && b == 1) cout << "2";
	else if (a == 1 && b == 2) cout << "3";
	else if (a == 1 && b == 3) cout << "4";
	else if (a == 1 && b == 4) cout << "5";
	else if (a == 1 && b == 5) cout << "6";
	else if (a == 1 && b == 6) cout << "7";
	else if (a == 1 && b == 7) cout << "8";
	else if (a == 1 && b == 8) cout << "9";
	else if (a == 1 && b == 9) cout << "10";
	else if (a == 2 && b == 1) cout << "3";
	else if (a == 2 && b == 2) cout << "4";
	else if (a == 2 && b == 3) cout << "5";
	else if (a == 2 && b == 4) cout << "6";
	else if (a == 2 && b == 5) cout << "7";
	else if (a == 2 && b == 6) cout << "8";
	else if (a == 2 && b == 7) cout << "9";
	else if (a == 2 && b == 8) cout << "10";
	else if (a == 2 && b == 9) cout << "11";
	else if (a == 3 && b == 1) cout << "4";
	else if (a == 3 && b == 2) cout << "5";
	else if (a == 3 && b == 3) cout << "6";
	else if (a == 3 && b == 4) cout << "7";
	else if (a == 3 && b == 5) cout << "8";
	else if (a == 3 && b == 6) cout << "9";
	else if (a == 3 && b == 7) cout << "10";
	else if (a == 3 && b == 8) cout << "11";
	else if (a == 3 && b == 9) cout << "12";
	else if (a == 4 && b == 1) cout << "5";
	else if (a == 4 && b == 2) cout << "6";
	else if (a == 4 && b == 3) cout << "7";
	else if (a == 4 && b == 4) cout << "8";
	else if (a == 4 && b == 5) cout << "9";
	else if (a == 4 && b == 6) cout << "10";
	else if (a == 4 && b == 7) cout << "11";
	else if (a == 4 && b == 8) cout << "12";
	else if (a == 4 && b == 9) cout << "13";
	else if (a == 5 && b == 1) cout << "6";
	else if (a == 5 && b == 2) cout << "7";
	else if (a == 5 && b == 3) cout << "8";
	else if (a == 5 && b == 4) cout << "9";
	else if (a == 5 && b == 5) cout << "10";
	else if (a == 5 && b == 6) cout << "11";
	else if (a == 5 && b == 7) cout << "12";
	else if (a == 5 && b == 8) cout << "13";
	else if (a == 5 && b == 9) cout << "14";
	else if (a == 6 && b == 1) cout << "7";
	else if (a == 6 && b == 2) cout << "8";
	else if (a == 6 && b == 3) cout << "9";
	else if (a == 6 && b == 4) cout << "10";
	else if (a == 6 && b == 5) cout << "11";
	else if (a == 6 && b == 6) cout << "12";
	else if (a == 6 && b == 7) cout << "13";
	else if (a == 6 && b == 8) cout << "14";
	else if (a == 6 && b == 9) cout << "15";
	else if (a == 7 && b == 1) cout << "8";
	else if (a == 7 && b == 2) cout << "9";
	else if (a == 7 && b == 3) cout << "10";
	else if (a == 7 && b == 4) cout << "11";
	else if (a == 7 && b == 5) cout << "12";
	else if (a == 7 && b == 6) cout << "13";
	else if (a == 7 && b == 7) cout << "14";
	else if (a == 7 && b == 8) cout << "15";
	else if (a == 7 && b == 9) cout << "16";
	else if (a == 8 && b == 1) cout << "9";
	else if (a == 8 && b == 2) cout << "10";
	else if (a == 8 && b == 3) cout << "11";
	else if (a == 8 && b == 4) cout << "12";
	else if (a == 8 && b == 5) cout << "13";
	else if (a == 8 && b == 6) cout << "14";
	else if (a == 8 && b == 7) cout << "15";
	else if (a == 8 && b == 8) cout << "16";
	else if (a == 8 && b == 9) cout << "17";
	else if (a == 9 && b == 1) cout << "10";
	else if (a == 9 && b == 2) cout << "11";
	else if (a == 9 && b == 3) cout << "12";
	else if (a == 9 && b == 4) cout << "13";
	else if (a == 9 && b == 5) cout << "14";
	else if (a == 9 && b == 6) cout << "15";
	else if (a == 9 && b == 7) cout << "16";
	else if (a == 9 && b == 8) cout << "17";
	else if (a == 9 && b == 9) cout << "18";
}
